name: "Build unitypackage"

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  packageName: "org.kb10uy.eye-pointer-installer"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Build"
        id: "build"
        uses: "docker://ghcr.io/rerigferl/vpm-packager:latest"
        with:
          args: "-z -u"

      - name: "Create Release"
        uses: "softprops/action-gh-release@v1"
        if: ${{ steps.build.outputs.package-version != '0.0.0' }}
        with:
          tag_name: ${{ steps.build.outputs.package-version }}
          files: |
            ${{ steps.build.outputs.zip-path }}
            ${{ steps.build.outputs.unitypackage-path }}
            ${{ steps.build.outputs.manifest-path }}
